version: '3'

services:

  app:
    image: ruby:2.7.1
    working_dir: /var/www/html
    command: bundle exec rails server -b 0.0.0.0 -p 3000
    env_file: .env
    volumes:
      - .:/var/www/html
      - local_gems:/usr/local/bundle
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0.18
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD:
    volumes:
      - .:/var/www/html
      - db:/var/lib/mysql
    ports:
      - "33061:3306"

volumes:
  local_gems:
  db: